/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package former;

import former.Cirkel;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author darre01
 */
public class FormJPanel extends javax.swing.JPanel {
private String val="";
ArrayList<Form> former = new ArrayList<>();
FileManager fmgr = new FileManager();
    /**
     * Creates new form FormJPanel
     */
    public FormJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnRensa = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        rbtnCirkel = new javax.swing.JRadioButton();
        rbtnTriangel = new javax.swing.JRadioButton();
        rbtnRektangel = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        hämtaBtn = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        btnRensa.setText("Rensa");
        btnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensaActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnCirkel);
        rbtnCirkel.setText("Cirkel");
        rbtnCirkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCirkelActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTriangel);
        rbtnTriangel.setText("Triangel");
        rbtnTriangel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTriangelActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnRektangel);
        rbtnRektangel.setText("Rektangel");

        saveBtn.setText("Spara");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        hämtaBtn.setText("Hämta");
        hämtaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hämtaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnCirkel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(rbtnTriangel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnRektangel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRensa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hämtaBtn)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRensa)
                    .addComponent(btnStart)
                    .addComponent(rbtnCirkel)
                    .addComponent(rbtnTriangel)
                    .addComponent(rbtnRektangel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(hämtaBtn))
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensaActionPerformed
       former.clear();
       val="";
       repaint();
    }//GEN-LAST:event_btnRensaActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
       val="Start";
       repaint();
    }//GEN-LAST:event_btnStartActionPerformed

    private void rbtnCirkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCirkelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCirkelActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        System.out.println("x-koord: "+evt.getX()+", y-koord: "+evt.getY());
        int x = evt.getX();
        int y = evt.getY();
        
        if (this.rbtnRektangel.isSelected()) {
        int b=(int)(Math.random()*50)+5;
        int h=(int)(Math.random()*50)+5;
        former.add(new Rektangel(x, y, b, h));
       repaint();
        } else if (this.rbtnCirkel.isSelected()) {
 int radie= (int)(Math.random()*60)+10;
former.add(new Cirkel(x, y, radie));
repaint();
        } else if (this.rbtnTriangel.isSelected()) {
        int b=(int)(Math.random()*50)+5;
        int h=(int)(Math.random()*50)+5;
        former.add(new Triangel(x,y,b,h));
        repaint();
        }
       
    }//GEN-LAST:event_formMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        fmgr.saveToFile(former);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void hämtaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hämtaBtnActionPerformed
        // TODO add your handling code here:
        former=fmgr.readFromFile();
        repaint();
    }//GEN-LAST:event_hämtaBtnActionPerformed

    private void rbtnTriangelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTriangelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTriangelActionPerformed
@Override
protected void paintComponent(Graphics g){
    super.paintComponent(g);
    for (int i = 0; i < former.size(); i++) {
        former.get(i).draw(g);
        
    }
}
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRensa;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hämtaBtn;
    private javax.swing.JRadioButton rbtnCirkel;
    private javax.swing.JRadioButton rbtnRektangel;
    private javax.swing.JRadioButton rbtnTriangel;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
